apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-pod
  template:
    metadata:
      labels:
        app: hpa-pod
    spec:
      restartPolicy: Always
      containers:
      - name: hpa-pod
        image: guybarrette/kuard:latest
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "16Mi"
            cpu: "100m"
          limits:
            memory: "32Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hpa-pod    
